### ISSUE TITLE
Sniffy - stack trace is missing line breaks

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#120]
![image](https://cloud.githubusercontent.com/assets/4654384/13728061/d44d1c8a-e91b-11e5-8189-0c3d850705ae.png)

Environment: [sniffy-demo](https://github.com/sniffy/sniffy-demo) running on heroku with following Procfile:

> web:    java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT target/petclinic.war

**Comment by bedrin** [comment]
Thinkning out loud - since stacktraces and SQL queries in enterprise world are huge it would be cool to show only a part of code by default and make it expandable on click like shown here:
http://stackoverflow.com/questions/20255458/expanding-a-div-to-reveal-overflow-on-click

Also for stacktraces we could collapse method calls from the same  framework like Hibernate, Spring, Tomcat, e.t.c. - it should be a separate issue I guess

**Comment by mudalov** [comment]
Looking on it, will also add expanding of huge stack traces. Lets address collapsing methods of same framework in separate issue.

**Comment by bedrin** [comment]
Ok. BTW, on my windows laptop linebreaks are fine

**Comment by mudalov** [comment]
hljs don't like unix like '\n' line separators. replacing them to '\r\n' fixes the issue
