### ISSUE TITLE
Console error with Firefox

### ISSUE THREAD

**Issue by roberthunt** [sniffy/sniffy#149]
I'm getting this error in the browser and firebug consoles when using Firefox 46.0 on OS X:

![screen shot 2016-05-04 at 10 15 19](https://cloud.githubusercontent.com/assets/567676/15009963/88e91b24-11e1-11e6-8472-61c37c580d52.png)

This is with Sniffy 3.0.7 on your demo application

**Comment by bedrin** [comment]
Thanks, I'll take a look at it

**Comment by bedrin** [comment]
Fixed in 3.1.0-SNAPSHOT
