### ISSUE TITLE
Sniffy XHR wrapper is not compatible with zone.js

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#266]
Causing UI to freeze until request is completed

Looks like XMLHttpRequest wrapper from zone.js isn't compatible with sniffy wrapper
https://github.com/sniffy/sniffy-ui/blob/master/src/sniffy.js#L458

Another possible reason is that Sniffy doesn't support XMLHttpRequest2 (new API with on*() methods)

Reported by @viosng

**Comment by bedrin** [comment]
Fixed in 3.1.1

**Comment by viosng** [comment]
Thanks!
