### ISSUE TITLE
Firefox widget position shifted

### ISSUE THREAD

**Issue by Simulant87** [sniffy/sniffy#328]
In Firefox (52.0.1) the Sniffy widget is a bit shifted to the bottom, so that the number of the executed queries is not readable. See the image in the link [https://i.stack.imgur.com/JKdSw.png](https://i.stack.imgur.com/JKdSw.png). In Chrome it looks good.

But in both browsers the headlines of the tabs in the pop-up could need a bit more space below. The lower part of the "p" of Top SQL is not completely visible. See this image [https://i.stack.imgur.com/QgaI5.png](https://i.stack.imgur.com/QgaI5.png).

**Comment by bedrin** [comment]
Fixed in 3.1.3

**Comment by bedrin** [comment]
![image](https://cloud.githubusercontent.com/assets/4654384/24332535/b7c80430-1250-11e7-948d-ffdd60499713.png)

**Comment by bedrin** [comment]
@Simulant87 thanks for reporting! :thumbsup:

**Comment by Simulant87** [comment]
wow. That was fast. Like your tool very much.
