### ISSUE TITLE
Poll - how do you use Sniffy?

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#361]
Hi everyone! Sniffy author here.

We have reached a 100 stars on GitHub recently but I didn't have a chance to do any significant development in Sniffy in past year.

Sniffy has three main functionalities (which are quite different) and I need your input to make a decision on future of the project.

Can you please vote what functions of Sniffy do you use/like/consider most useful?

[![](https://api.gh-polls.com/poll/01DGSM6BPSAS7FESHR6H1JCK4K/SQL%20profiler%20widget)](https://api.gh-polls.com/poll/01DGSM6BPSAS7FESHR6H1JCK4K/SQL%20profiler%20widget/vote)
[![](https://api.gh-polls.com/poll/01DGSM6BPSAS7FESHR6H1JCK4K/SQL%20asserts%20in%20unit%20tests)](https://api.gh-polls.com/poll/01DGSM6BPSAS7FESHR6H1JCK4K/SQL%20asserts%20in%20unit%20tests/vote)
[![](https://api.gh-polls.com/poll/01DGSM6BPSAS7FESHR6H1JCK4K/Simulating%20network%20issues%20-%20fault%20tolerance%20testing)](https://api.gh-polls.com/poll/01DGSM6BPSAS7FESHR6H1JCK4K/Simulating%20network%20issues%20-%20fault%20tolerance%20testing/vote)

Thanks,
 Dmitry.

**Comment by bedrin** [comment]
@ckorakidis Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@baitcenter Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Rodrigo94 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Leaking Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@devmake Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@nfaupel Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@steck Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@udalovas Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Tapac Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@walterfrs Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@liudng Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@rohinsha Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@d0k1 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Rumpam Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@joelxr Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@roberthunt Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@udalmik Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@brunocvcunha Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@mikhail Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?-vnukov
@ShaneDelmore Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@sriio Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Jnster Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@oak Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?-tree
@nasapra Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@smagellan Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@DavidValin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kshchepanovskyi Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ansyeow Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@anjingxz Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@pdxbd Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@RobertTrebor Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@es0329 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@nemesiscodex Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@anjeludo Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@lanwen Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@zak905 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@SergeyBudnik Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@szquadri Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@antarr Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@alexogar Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@StephenOTT Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@paulwhitby Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@chrisreichel Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@droidnxs Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@sidney3172 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@afanvad Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@tobijdc Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@bingoohuang Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@beat2 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@yatsan Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@siepkes Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Litee Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@knalli Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kryusvy Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@nbosa Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@RenanPalmeira Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@abevieiramota Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@amirkaromashkin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jaxlucas Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ul8422 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@whitfin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@bassista Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ammachado Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@MarcGiffing Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@viosng Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Simulant87 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ericsiber Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jarek Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?-przygodzki
@astrapi69 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ttddyy Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kolunsha Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ovbedrina Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@bedrin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@edwardchanjw Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kuhnroyal Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@disunbow Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Sonictherocketman Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ethfun Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@othmaan Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jayanderson Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@tobh Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jimmyMaci Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@sepe81 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@RobertDiPaolo Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@nathankurtyka Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@manju Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?-reddys
@jgatcher Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@florianschmitt Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@sherpaDai Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@VictorZelenin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@charanyarajagopalan Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jangalinski Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ibrahiem96 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@vladmihalcea Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@mweisshaupt1988 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@miloszpiglas Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@dkorobtsov Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@MacKittipat Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ccronemberger Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@diegocrzt Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?

**Comment by bedrin** [comment]
@siepkes Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Litee Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@knalli Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kryusvy Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@nbosa Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@RenanPalmeira Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@abevieiramota Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@amirkaromashkin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jaxlucas Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ul8422 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@whitfin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@bassista Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ammachado Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@MarcGiffing Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@viosng Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Simulant87 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ericsiber Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jarek Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?-przygodzki
@astrapi69 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ttddyy Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kolunsha Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ovbedrina Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@bedrin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@edwardchanjw Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@kuhnroyal Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@disunbow Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@Sonictherocketman Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ethfun Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@othmaan Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jayanderson Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@tobh Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jimmyMaci Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@sepe81 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@RobertDiPaolo Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@nathankurtyka Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@manju Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?-reddys
@jgatcher Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@florianschmitt Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@sherpaDai Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@VictorZelenin Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@charanyarajagopalan Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@jangalinski Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ibrahiem96 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@vladmihalcea Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@mweisshaupt1988 Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@miloszpiglas Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@dkorobtsov Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@MacKittipat Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@ccronemberger Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?
@diegocrzt Hi there. Sniffy author here! Can you please vote what functions of Sniffy do you use/like/consider most useful?

**Comment by lanwen** [comment]
Is that really appropriate way of getting feedback?

**Comment by ul8422** [comment]
Hey. :) I just used it into my tests to control sql query count.

сб, 27 июл. 2019 г. в 18:39, Kirill Merkushev <notifications@github.com>:

**Comment by siepkes** [comment]
Not actually using it; Just starred it because I thought it might be interesting for future use.

**Comment by jarek** [comment]
I never even starred this repository. Please be a little more careful tagging.

**Comment by bedrin** [comment]
Thanks a lot for feedback. We got 90 votes - fantastic result!
