### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by sides-flow** [sniffy/sniffy#501]
Hi :)
I'm trying to make a java agent and I'm using some of your code as reference.
I stumbled across a code that I think might be incorrect:
https://github.com/sniffy/sniffy/blob/9b1225719ff892f885f1e8c82eac478d11ce6249/sniffy-core/src/main/java/io/sniffy/socket/SnifferInputStream.java#L137

In the referenced line, isn't it supposed to be `delegate.skip(n);` ?
If not, why is that different than all of the other wrappers?

**Comment by bedrin** [comment]
Hi!

It's done on purpose - default implementation of `skip` method in `InputStream` would just call `read` and ignore the results.
`read` method is overriden in `SnifferInputStream` and would invoke relevant delegate method.

It allows Sniffy to capture all the traffic, even if if it was skipped by the application.

Hope it makes sense.

**Comment by sides-flow** [comment]
Makes a lot of sense. Nice! I missed the part where the implementation of `skip` calls `read`.
In my case, I don't want to sniff the data that was skipped, so I'm gonna use `delegate.skip(n);`.
Thanks for your help!
