### ISSUE TITLE
UI must be enableble using request parameter

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#83]

**Comment by mudalov** [comment]
Filter has global "enabled". As I understand new query parameter should have higher priority, is it correct?

**Comment by mudalov** [comment]
What about parameter name? Simple "sniffyEnabled", or more specific, like "trackSqlQueries"?

**Comment by bedrin** [comment]
@mudalov yes, request parameter should have higher priority. Sniffy will soon learn how to intercept all network connections, not only JDBC, so parameter name should be rather just sniffy like "/foo?bar=42&sniffy"

**Comment by bedrin** [comment]
Actually we need to store this flag in cookies - otherwise request parameter will work only on a single request. All XHR requests won't be processsed by Sniffy. Reopening

**Comment by karlkilden** [comment]
What's the use case for this? UI sensitive work? It can't be actual activation because Security through obscurity does not work, especially not for open source. Also, you hardly want the overhead anyways

**Comment by bedrin** [comment]
@karlkilden there are environments like UAT which are used both by business users for trying new features and be engineering team for testing, e.t.c. Business users should not see the Sniffy widget - it will raise undesirable questions, especially if sniffy will render some warning or something
